<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.admin.label.strategy.native' shared service.

include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/Translator/LabelTranslatorStrategyInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/Translator/NativeLabelTranslatorStrategy.php';

return $this->services['sonata.admin.label.strategy.native'] = new \Sonata\AdminBundle\Translator\NativeLabelTranslatorStrategy();
