<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.block.exception.renderer.inline_debug' shared service.

include_once $this->targetDirs[3].'/vendor/sonata-project/block-bundle/Exception/Renderer/RendererInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/block-bundle/Exception/Renderer/InlineDebugRenderer.php';

return $this->services['sonata.block.exception.renderer.inline_debug'] = new \Sonata\BlockBundle\Exception\Renderer\InlineDebugRenderer(${($_ = isset($this->services['templating']) ? $this->services['templating'] : $this->load(__DIR__.'/getTemplatingService.php')) && false ?: '_'}, 'SonataBlockBundle:Block:block_exception_debug.html.twig', true, true);
