<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.admin.manipulator.acl.admin' shared service.

include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/Util/AdminAclManipulatorInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/Util/AdminAclManipulator.php';

return $this->services['sonata.admin.manipulator.acl.admin'] = new \Sonata\AdminBundle\Util\AdminAclManipulator('Sonata\\AdminBundle\\Security\\Acl\\Permission\\MaskBuilder');
