<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.admin.event.extension' shared service.

include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/Admin/AdminExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/Admin/AbstractAdminExtension.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/Event/AdminEventExtension.php';

return $this->services['sonata.admin.event.extension'] = new \Sonata\AdminBundle\Event\AdminEventExtension(${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'});
