<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.admin.route.path_info' shared service.

include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/Builder/RouteBuilderInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/Route/PathInfoBuilder.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/Model/AuditManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/Model/AuditManager.php';

return $this->services['sonata.admin.route.path_info'] = new \Sonata\AdminBundle\Route\PathInfoBuilder(${($_ = isset($this->services['sonata.admin.audit.manager']) ? $this->services['sonata.admin.audit.manager'] : $this->services['sonata.admin.audit.manager'] = new \Sonata\AdminBundle\Model\AuditManager($this)) && false ?: '_'});
