<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG4iey4g\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG4iey4g/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerG4iey4g.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerG4iey4g\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerG4iey4g\appDevDebugProjectContainer(array(
    'container.build_hash' => 'G4iey4g',
    'container.build_id' => 'dca6559d',
    'container.build_time' => 1516005158,
));
