<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXx5azyv\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXx5azyv/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXx5azyv.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXx5azyv\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXx5azyv\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Xx5azyv',
    'container.build_id' => 'f73ace45',
    'container.build_time' => 1516057447,
));
