<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWgtvhzn\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWgtvhzn/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWgtvhzn.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWgtvhzn\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWgtvhzn\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Wgtvhzn',
    'container.build_id' => 'c267733d',
    'container.build_time' => 1527775755,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWgtvhzn');
